Update zpush to 2.6.2
mail-in-a-box/mailinabox pull request #1932
Opened 2021-02-23 21:18 UTC by davDevOps

Z-Push Bug Fixes:

Outlook Calendar Stuck in Sync
PHP 7.4 related fix
IMAP and CardDav contributions

2021-02-27 18:00 UTC, jvolkenant requested changes

2021-02-27 18:00 UTC, jvolkenant commented on setup/webmail.sh
> +#      4.0.4 is in a different compression format (.tgz)
Should list only the version being installed and not future versions.  There was work when carddav was updated before and will likely be needed again (i.e. a standalone PR)

2021-02-27 18:00 UTC, jvolkenant commented on setup/webmail.sh
> +# CARDDAV_HASH=7035a68b392c7e698f5dbcfe7be7eea1d7dff21a
not needed until we are installing that version.

2021-02-27 18:00 UTC, jvolkenant commented
This should really be 3 commits (but would be fine with a renamed PR in the future)

2021-02-27 18:27 UTC, davDevOps commented
Sorry!  This was my first commit, so I'm still kinda new to this.  Just wanted to take the version updating off somebody else's plate.

2021-02-28 13:21 UTC, JoshData commented
Merged via the above commit, with some changes.

2021-02-28 13:21 UTC, closed without merging

2021-02-28 20:11 UTC, jvolkenant commented
> 
> 
> Sorry! This was my first commit, so I'm still kinda new to this. Just wanted to take the version updating off somebody else's plate.

Not a problem, it was helpful (and looks to be accepted!) good job. 

The reason why It would be best to submit them as different pull requests is it is easier to roll back the commit for one of the changes and not happen to roll back all of them (i.e. if we had to remove the zpush commit, it didnt also happen to roll back the roundcube one.

Thanks again for your PR.